---
deployment:
  tasks:
    - export DEPLOYPATH=/home/qjwmwinf/public_html
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp script.js $DEPLOYPATH
    - /bin/cp profile.png $DEPLOYPATH
    # Add other files or directories here if needed
    # /bin/cp -R assets $DEPLOYPATH
